version: "3.9"

services:
  products-api:
    build: ./backend/products-api
    container_name: products-api
    ports:
      - "8000:8000"

  orders-api:
    build: ./backend/orders-api
    container_name: orders-api
    ports:
      - "8001:8001"
    environment:
      INVENTORY_API_URL: http://inventory-api:8002/api/inventory/reduce
    depends_on:
      - inventory-api

  inventory-api:
    build: ./backend/inventory-api
    container_name: inventory-api
    ports:
      - "8002:8002"

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_PRODUCTS_API_URL: http://products-api:8000
      NEXT_PUBLIC_ORDERS_API_URL: http://orders-api:8001
    depends_on:
      - products-api
      - orders-api
      - inventory-api
