version: "3.9"

services:
  products-api:
    build: ./backend/products-api
    container_name: products-api
    ports:
      - "8000:8000"
    volumes:
      - ./backend/products-api/retail.db:/app/retail.db


  orders-api:
    build: ./backend/orders-api
    container_name: orders-api
    ports:
      - "8001:8001"
    environment:
      INVENTORY_API_URL: http://inventory-api:8002/api/inventory/reduce
    depends_on:
      - inventory-api
    volumes:
      - ./backend/orders-api/orders.db:/app/orders.db

  inventory-api:
    build: ./backend/inventory-api
    container_name: inventory-api
    ports:
      - "8002:8002"
    volumes:
      - ./backend/inventory-api/inventory.db:/app/inventory.db

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      # 1. CLIENT-SIDE (Browser)
      # The browser is outside Docker, so it uses localhost
      - NEXT_PUBLIC_PRODUCTS_API_URL=http://localhost:8000
      - NEXT_PUBLIC_ORDERS_API_URL=http://localhost:8001
      - NEXT_PUBLIC_INVENTORY_API_URL=http://localhost:8002

      # 2. SERVER-SIDE (Next.js Node Server)
      # If getStaticProps/getServerSideProps runs, it is INSIDE Docker.
      # It must use the container names.
      - INTERNAL_PRODUCTS_API_URL=http://products-api:8000
      - INTERNAL_ORDERS_API_URL=http://orders-api:8001
      - INTERNAL_INVENTORY_API_URL=http://inventory-api:8002
    depends_on:
      - products-api
      - orders-api
      - inventory-api
