apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-frontend-to-backends
  namespace: microservices
spec:
  podSelector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - products
          - orders
          - inventory
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: frontend
      ports:
        - port: 5001
          protocol: TCP
        - port: 5002
          protocol: TCP
        - port: 5003
          protocol: TCP
