apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: dev
data:
  # Internal URLs (Used by Next.js server-side methods like getServerSideProps)
  INTERNAL_PRODUCTS_API_URL: "http://products-api-service:80"
  INTERNAL_ORDERS_API_URL: "http://orders-api-service:80"
  INTERNAL_INVENTORY_API_URL: "http://inventory-api-service:80"
  # External URLs (Used by the user's browser via Ingress) - Will be updated in Phase 4 Step 3
  NEXT_PUBLIC_PRODUCTS_API_URL: "/api/products" 
  NEXT_PUBLIC_ORDERS_API_URL: "/api/orders"