apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecommerce-ingress
  namespace: dev
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/certificate-arn: 'arn:aws:acm:us-east-1:440491339319:certificate/42c49e2a-2d1a-4409-a145-dd06cda11aef'
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/load-balancer-attributes: deletion_protection.enabled=false
    alb.ingress.kubernetes.io/group.name: shared-alb
spec:
  ingressClassName: alb
  rules:
  - host: umdprojectgroup.com
    http:
      paths:
      # API routes
      - path: /api/orders
        pathType: Prefix
        backend:
          service:
            name: orders-api-service
            port: 
              number: 80
      
      - path: /api/products
        pathType: Prefix
        backend:
          service:
            name: products-api-service
            port: 
              number: 80
      
      - path: /api/inventory
        pathType: Prefix
        backend:
          service:
            name: inventory-api-service
            port: 
              number: 80
      
      # Frontend (MUST BE LAST)
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port: 
              number: 80
